//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evaluate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public Answer()
        {
            this.EvaluationDetails = new HashSet<EvaluationDetail>();
            this.EvaluationQuestions = new HashSet<EvaluationQuestion>();
        }
    
        public int AnswerId { get; set; }
        public Nullable<int> QuestionId { get; set; }
        public string AnswerName { get; set; }
        public Nullable<bool> IsCorrect { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual ICollection<EvaluationDetail> EvaluationDetails { get; set; }
        public virtual ICollection<EvaluationQuestion> EvaluationQuestions { get; set; }
    }
}
