//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evaluate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Career
    {
        public Career()
        {
            this.StudentCareers = new HashSet<StudentCareer>();
            this.Subjects = new HashSet<Subject>();
            this.Evaluations = new HashSet<Evaluation>();
        }
    
        public int CareerId { get; set; }
        public string CareerName { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> QuestionsInExam { get; set; }
        public Nullable<int> MinScore { get; set; }
    
        public virtual ICollection<StudentCareer> StudentCareers { get; set; }
        public virtual ICollection<Subject> Subjects { get; set; }
        public virtual ICollection<Evaluation> Evaluations { get; set; }
    }
}
