//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evaluate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Link
    {
        public int LinkId { get; set; }
        public string LinkName { get; set; }
        public string Description { get; set; }
        public string Url { get; set; }
        public string ImageName { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
