//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evaluate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plan
    {
        public Plan()
        {
            this.StudentCareers = new HashSet<StudentCareer>();
        }
    
        public int PlanId { get; set; }
        public string PlanName { get; set; }
        public Nullable<int> Months { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Interval { get; set; }
        public Nullable<int> Increment { get; set; }
    
        public virtual ICollection<StudentCareer> StudentCareers { get; set; }
    }
}
