//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evaluate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.Answers = new HashSet<Answer>();
            this.EvaluationDetails = new HashSet<EvaluationDetail>();
            this.EvaluationQuestions = new HashSet<EvaluationQuestion>();
        }
    
        public int QuestionId { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public string QuestionName { get; set; }
        public Nullable<int> Difficulty { get; set; }
        public Nullable<bool> Status { get; set; }
        public string ImageName { get; set; }
    
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual ICollection<EvaluationDetail> EvaluationDetails { get; set; }
        public virtual ICollection<EvaluationQuestion> EvaluationQuestions { get; set; }
    }
}
