//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evaluate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentCareer
    {
        public int Id { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> CareerId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> PlanId { get; set; }
        public Nullable<int> Months { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string Interval { get; set; }
        public Nullable<int> Increment { get; set; }
    
        public virtual Career Career { get; set; }
        public virtual Student Student { get; set; }
        public virtual Plan Plan { get; set; }
    }
}
