//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evaluate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Evaluations = new HashSet<Evaluation>();
            this.StudentCareers = new HashSet<StudentCareer>();
        }
    
        public int StudentId { get; set; }
        public string UserId { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual ICollection<Evaluation> Evaluations { get; set; }
        public virtual ICollection<StudentCareer> StudentCareers { get; set; }
    }
}
