//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evaluate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public Subject()
        {
            this.Evaluations = new HashSet<Evaluation>();
            this.Questions = new HashSet<Question>();
        }
    
        public int SubjectId { get; set; }
        public Nullable<int> CareerId { get; set; }
        public string SubjectName { get; set; }
        public Nullable<int> QuestionsInExam { get; set; }
        public Nullable<int> MinScore { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Career Career { get; set; }
        public virtual ICollection<Evaluation> Evaluations { get; set; }
        public virtual ICollection<Question> Questions { get; set; }
    }
}
